insert into tb_article(title,description,author,image,create_date,category_id) values('C#','How can I learn without think more','metra yim on','download.jpg','10-3-2012',1),
('Java','How can I learn without think more','metra','download.jpg','10-3-2012',1),
('SQL','How can I learn without think more','metra','download.jpg','10-3-2012',3),
('Mybatis','How can I learn without think more','metra','download.jpg','10-3-2012',4),
('Kaka','How can I learn without think more','metra','download.jpg','10-3-2012',2),
('Friday','How can I learn without think more','metra','download.jpg','10-3-2012',3  ),
('Java','How can I learn without think more','metra','download.jpgg','10-3-2012',1),
('SQL','How can I learn without think more','metra','download.jpg','10-3-2012',3),
('Mybatis','How can I learn without think more','metra','download.jpg','10-3-2012',4),
('Kaka','How can I learn without think more','metra','download.jpg','10-3-2012',2),
('Friday','How can I learn without think more','metra','download.jpg','10-3-2012',3  ),
('Java','How can I learn without think more','metra','download.jpg','10-3-2012',1),
('SQL','How can I learn without think more','metra','download.jpg','10-3-2012',3),
('Mybatis','How can I learn without think more','metra','download.jpg','10-3-2012',4),
('Kaka','How can I learn without think more','metra','download.jpg','10-3-2012',2),
('Friday','How can I learn without think more','metra','download.jpg','10-3-2012',3  ),
('Java','How can I learn without think more','metra','download.jpg','10-3-2012',1),
('SQL','How can I learn without think more','metra','download.jpg','10-3-2012',3),
('Mybatis','How can I learn without think more','metra','download.jpg','10-3-2012',4),
('Kaka','How can I learn without think more','metra','download.jpg','10-3-2012',2),
('Friday','How can I learn without think more','metra','download.jpg','10-3-2012',3  ),

('Kaka','How can I learn without think more','metra','paper.jpg','10-3-2012',2),
('Java','How can I learn without think more','metra','download.jpg','10-3-2012',1),
('SQL','How can I learn without think more','metra','download.jpg','10-3-2012',3),
('Mybatis','How can I learn without think more','metra','download.jpg','10-3-2012',4),
('Kaka','How can I learn without think more','metra','download.jpg','10-3-2012',2),
('Friday','How can I learn without think more','metra','download.jpg','10-3-2012',3  ),
('Java','How can I learn without think more','metra','download.jpgg','10-3-2012',1),
('SQL','How can I learn without think more','metra','download.jpg','10-3-2012',3),
('Mybatis','How can I learn without think more','metra','download.jpg','10-3-2012',4),
('Kaka','How can I learn without think more','metra','download.jpg','10-3-2012',2),
('Friday','How can I learn without think more','metra','download.jpg','10-3-2012',3  ),
('Java','How can I learn without think more','metra','download.jpg','10-3-2012',1),
('SQL','How can I learn without think more','metra','download.jpg','10-3-2012',3),
('Mybatis','How can I learn without think more','metra','download.jpg','10-3-2012',4),
('Kaka','How can I learn without think more','metra','download.jpg','10-3-2012',2),
('Friday','How can I learn without think more','metra','download.jpg','10-3-2012',3  ),
('Java','How can I learn without think more','metra','download.jpg','10-3-2012',1),
('SQL','How can I learn without think more','metra','download.jpg','10-3-2012',3),
('Mybatis','How can I learn without think more','metra','download.jpg','10-3-2012',4),
('Kaka','How can I learn without think more','metra','download.jpg','10-3-2012',2),
('Friday','How can I learn without think more','metra','download.jpg','10-3-2012',3  ),

('Kaka','How can I learn without think more','metra','paper.jpg','10-3-2012',2),
('Java','How can I learn without think more','metra','download.jpg','10-3-2012',1),
('SQL','How can I learn without think more','metra','download.jpg','10-3-2012',3),
('Mybatis','How can I learn without think more','metra','download.jpg','10-3-2012',4),
('Kaka','How can I learn without think more','metra','download.jpg','10-3-2012',2),
('Friday','How can I learn without think more','metra','download.jpg','10-3-2012',3  ),
('Java','How can I learn without think more','metra','download.jpgg','10-3-2012',1),
('SQL','How can I learn without think more','metra','download.jpg','10-3-2012',3),
('Mybatis','How can I learn without think more','metra','download.jpg','10-3-2012',4),
('Kaka','How can I learn without think more','metra','download.jpg','10-3-2012',2),
('Friday','How can I learn without think more','metra','download.jpg','10-3-2012',3  ),
('Java','How can I learn without think more','metra','download.jpg','10-3-2012',1),
('SQL','How can I learn without think more','metra','download.jpg','10-3-2012',3),
('Mybatis','How can I learn without think more','metra','download.jpg','10-3-2012',4),
('Kaka','How can I learn without think more','metra','download.jpg','10-3-2012',2),
('Friday','How can I learn without think more','metra','download.jpg','10-3-2012',3  ),
('Java','How can I learn without think more','metra','download.jpg','10-3-2012',1),
('SQL','How can I learn without think more','metra','download.jpg','10-3-2012',3),
('Mybatis','How can I learn without think more','metra','download.jpg','10-3-2012',4),
('Kaka','How can I learn without think more','metra','download.jpg','10-3-2012',2),
('Friday','How can I learn without think more','metra','download.jpg','10-3-2012',3  ),

('Kaka','How can I learn without think more','metra','paper.jpg','10-3-2012',2),
('Friday','How can I learn without think more','metra','paper.jpg','10-3-2012',3  );